APP.Router = Backbone.Router.extend({
    routes: {
        "" : "dashboard",
        "dashboard" : "dashboard",
        "jobs/add" : "addJob",
        "jobs/:id": "editJob"
    },

    initialize: function(){
        console.log("router initialized");
    },

    addJob: function(){
        console.log("addJob() route fired");
        APP.jobview = new APP.NewJobModelView();
        // render the view
        APP.jobview.render();
        // append it to the dom
        $('.jumbotron').html(APP.jobview.$el);
    },

    editJob: function(){
        // Grab the window href and store it in a local variable.
        var src = window.location.href;
        // Use underscore to grab the id portion of the href,
        // which by design will be the last index in the array
        // generated by running split("/").
        var id = _.last(src.split("/"));

        // Create an instance of the job model, which initially
        // only contains the id field that was generated in the
        // first step. Backbone then uses this id as a reference
        // when it executes fetch to identify which model data
        // to pull from the server. Within the success function
        // we then reference this model within the view instance
        // and then render and append this new view.
        APP.jobmodel = new APP.JobModel({_id: id});
        APP.jobmodel.fetch({
            success: function(){
                APP.jobmodelview = new APP.JobModelView({
                    model: APP.jobmodel,
                });
                APP.jobmodelview.render();
                $('.jumbotron').html(APP.jobmodelview.$el);
            }
        });
    },

    dashboard: function(){
        console.log("dashboard() route fired");
        APP.jobcollection = new APP.JobCollection();
        APP.jobcollection.fetch({
            success: function(){
                APP.jobcollectionview = new APP.JobCollectionView({
                    collection: APP.jobcollection
                });

                APP.jobcollectionview.render();
                // $('.jumbotron').children().remove();
                $('.jumbotron').html(APP.jobcollectionview.$el);
            }
        });
    }
});

APP.router = new APP.Router();
Backbone.history.start({root: "/"});